name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64-22.03.2
        fixup:
          - 1

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        uses: cmangla/gh-action-sdk@pr-hash-fixup-option
        env:
          ARCH: ${{ matrix.arch }}
          FEEDNAME: packages
          FIXUP: ${{ matrix.fixup }}

      - name: Move created packages to project dir
        run: cp bin/packages/${{ matrix.arch }}/packages_ci/*.ipk . || true

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch}}-packages
          path: |
            *.ipk
