name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wrtrel:
          - 22.03.2
        sdk:
          - x86-64
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Build rrredir package for OpenWRT
        uses: cmangla/gh-action-sdk@pr-hash-fixup-option
        env:
          ARCH: ${{ matrix.sdk }}-${{ matrix.wrtrel }}
          EXTRA_FEEDS: src-git|rrredir|${{ github.server_url }}/${{ github.repository }}.git^${{ github.sha }}
          PACKAGES: rrredir
          FIXUP: 1
          V: w # s=(stdout+stderr), w=warnings, c=commands

      - uses: actions/upload-artifact@v4
        with:
          name: rrredir_0.3_openwrt-${{ matrix.wrtrel }}_${{ matrix.sdk }}.ipk.d
          path: bin/packages/**/rrredir_*.ipk
