name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64-22.03
        fixup:
          - 1

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        uses: cmangla/gh-action-sdk@pr-hash-fixup-option
        env:
          ARCH: ${{ matrix.arch }}
          FIXUP: ${{ matrix.fixup }}
          CONTAINER: openwrt/sdk

      - name: Store packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch}}-packages
          path: "*.ipk"
